language: ruby
rvm:
  - 2.0.0
before_install:
  - "sudo apt-get update"
  - "sudo apt-get install vim-gnome"
  - "vim --version"
install: bundle
script: xvfb-run rake --format documentation
notifications:
  email: false
